extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_f3d_material_002_layer1_area1_lights;
extern Lights1 ccm_dl_f3d_material_001_layer1_area1_lights;
extern Lights1 ccm_dl_f3d_material_layer1_area1_lights;
extern u8 ccm_dl_StomachAcid3Ci4_ci4[];
extern u8 ccm_dl_StomachAcid3Ci4_ci4_pal_rgba16[];
extern u8 ccm_dl_blueflesh2_ci4[];
extern u8 ccm_dl_blueflesh2_ci4_pal_rgba16[];
extern u8 ccm_dl_bluepuss_ci4[];
extern u8 ccm_dl_bluepuss_ci4_pal_rgba16[];
extern u8 ccm_dl_blueflesh3_ci4[];
extern u8 ccm_dl_blueflesh3_ci4_pal_rgba16[];
extern Vtx ccm_dl_Lava_mesh_layer_5_vtx_cull[8];
extern Vtx ccm_dl_Lava_mesh_layer_5_vtx_0[12];
extern Gfx ccm_dl_Lava_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Lava2_mesh_layer_5_vtx_cull[8];
extern Vtx ccm_dl_Lava2_mesh_layer_5_vtx_0[12];
extern Gfx ccm_dl_Lava2_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Mesh_mesh_layer_1_vtx_0[18];
extern Gfx ccm_dl_Mesh_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Mesh_mesh_layer_1_vtx_1[18];
extern Gfx ccm_dl_Mesh_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Mesh_mesh_layer_1_vtx_2[18];
extern Gfx ccm_dl_Mesh_mesh_layer_1_tri_2[];
extern Gfx mat_ccm_dl_bottomstomachacid[];
extern Gfx mat_revert_ccm_dl_bottomstomachacid[];
extern Gfx mat_ccm_dl_stomachacid[];
extern Gfx mat_revert_ccm_dl_stomachacid[];
extern Gfx mat_ccm_dl_f3d_material_002_layer1_area1[];
extern Gfx mat_revert_ccm_dl_f3d_material_002_layer1_area1[];
extern Gfx mat_ccm_dl_f3d_material_001_layer1_area1[];
extern Gfx mat_revert_ccm_dl_f3d_material_001_layer1_area1[];
extern Gfx mat_ccm_dl_f3d_material_layer1_area1[];
extern Gfx mat_revert_ccm_dl_f3d_material_layer1_area1[];
extern Gfx ccm_dl_Lava_mesh_layer_5[];
extern Gfx ccm_dl_Lava2_mesh_layer_5[];
extern Gfx ccm_dl_Mesh_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
