extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern Lights1 sl_dl_pussplatformtop_layer1_area1_lights;
extern Lights1 sl_dl_pussplatformwalls_layer1_area1_lights;
extern Lights1 sl_dl_stomachacid_layer5_area1_lights;
extern u8 sl_dl_bluepuss_ci4[];
extern u8 sl_dl_bluepuss_ci4_pal_rgba16[];
extern u8 sl_dl_blueflesh2_ci4[];
extern u8 sl_dl_blueflesh2_ci4_pal_rgba16[];
extern u8 sl_dl_greenerbluePlasmaCi4_ci4[];
extern u8 sl_dl_greenerbluePlasmaCi4_ci4_pal_rgba16[];
extern Vtx sl_dl_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Mesh_mesh_layer_1_vtx_0[24];
extern Gfx sl_dl_Mesh_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Mesh_mesh_vtx_cull[8];
extern Vtx sl_dl_Mesh_mesh_vtx_0[32];
extern Gfx sl_dl_Mesh_mesh_tri_0[];
extern Vtx sl_dl_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx sl_dl_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx sl_dl_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_sl_dl_pussplatformtop_layer1_area1[];
extern Gfx mat_revert_sl_dl_pussplatformtop_layer1_area1[];
extern Gfx mat_sl_dl_pussplatformwalls_layer1_area1[];
extern Gfx mat_revert_sl_dl_pussplatformwalls_layer1_area1[];
extern Gfx mat_sl_dl_stomachacid_layer5_area1[];
extern Gfx mat_revert_sl_dl_stomachacid_layer5_area1[];
extern Gfx sl_dl_Mesh_mesh_layer_1[];
extern Gfx sl_dl_Mesh_mesh[];
extern Gfx sl_dl_Mesh_mesh_layer_5[];
extern Gfx sl_dl_material_revert_render_settings[];
