extern const GeoLayout blinking_mushroom_000_switch_opt1[];
extern const GeoLayout blinking_mushroom_000_switch_opt2[];
extern const GeoLayout blinking_mushroom_geo[];
extern u8 blinking_mushroom_lavender_rgba32[];
extern u8 blinking_mushroom_babyblue_rgba32[];
extern Vtx blinking_mushroom_Plant_mesh_layer_4_vtx_0[4];
extern Gfx blinking_mushroom_Plant_mesh_layer_4_tri_0[];
extern Gfx mat_blinking_mushroom_lavendar_material_002[];
extern Gfx mat_revert_blinking_mushroom_lavendar_material_002[];
extern Gfx mat_blinking_mushroom_blue_material_009[];
extern Gfx mat_revert_blinking_mushroom_blue_material_009[];
extern Gfx blinking_mushroom_Plant_mesh_layer_4[];
extern Gfx blinking_mushroom_Plant_mesh_layer_4_mat_override_lavendar_material_002_0[];
extern Gfx blinking_mushroom_Plant_mesh_layer_4_mat_override_blue_material_009_1[];
extern Gfx blinking_mushroom_material_revert_render_settings[];
