extern const GeoLayout goomba_000_switch_opt1[];
extern const GeoLayout goomba_geo[];
extern Lights1 goomba_Body_lights;
extern Lights1 goomba_Face_lights;
extern Lights1 goomba_Crazy_Face_lights;
extern Lights1 goomba_Feet_lights;
extern u8 goomba_goomba_body_rgba16_rgba16[];
extern u8 goomba_goomba_face_rgba16_rgba16[];
extern u8 goomba_goomba_face_blink_rgba16_rgba16[];
extern Vtx goomba_000_displaylist_mesh_layer_4_vtx_0[4];
extern Gfx goomba_000_displaylist_mesh_layer_4_tri_0[];
extern Vtx goomba_000_offset_002_mesh_layer_1_vtx_0[57];
extern Gfx goomba_000_offset_002_mesh_layer_1_tri_0[];
extern Vtx goomba_000_offset_003_mesh_layer_1_vtx_0[20];
extern Gfx goomba_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx goomba_000_offset_004_mesh_layer_1_vtx_0[20];
extern Gfx goomba_000_offset_004_mesh_layer_1_tri_0[];
extern Gfx mat_goomba_Body[];
extern Gfx mat_revert_goomba_Body[];
extern Gfx mat_goomba_Face[];
extern Gfx mat_goomba_Crazy_Face[];
extern Gfx mat_goomba_Feet[];
extern Gfx goomba_000_displaylist_mesh_layer_4[];
extern Gfx goomba_000_offset_002_mesh_layer_1[];
extern Gfx goomba_000_offset_002_mesh_layer_1_mat_override_Crazy_Face_0[];
extern Gfx goomba_000_offset_003_mesh_layer_1[];
extern Gfx goomba_000_offset_004_mesh_layer_1[];
extern Gfx goomba_material_revert_render_settings[];
